#!/bin/bash
# Pastry Release — 生产发布
# 流程：测试 → release 编译 → 去除符号 → 组装 → 签名 → DMG → 烟测 → 可选发布
# 用法: ./release.sh <version> [--publish] [--allow-dirty]
#   ./release.sh 1.0.1              # 仅构建 DMG
#   ./release.sh 1.0.1 --publish    # 构建 + 推 tag + 创建 GitHub Release
#   ./release.sh --auto-version     # 自动计算版本，仅构建本地 DMG
set -e
set -o pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="Pastry"
BUILD_DIR="$PROJECT_DIR/.build/release"
STAGING="$PROJECT_DIR/.release_staging"
DIST_DIR="$PROJECT_DIR/dist"
BUNDLE_ID="com.nekutai.pastry"
IDENTITY="${CODESIGN_IDENTITY:-Nekutai}"

# 解析参数
PUBLISH=false
ALLOW_DIRTY=false
AUTO_VERSION=false
VERSION=""
for arg in "$@"; do
    case "$arg" in
        --publish) PUBLISH=true ;;
        --allow-dirty) ALLOW_DIRTY=true ;;
        --auto-version) AUTO_VERSION=true ;;
        --*) echo "❌ 未知参数: $arg" >&2; exit 2 ;;
        *)
            [[ -z "$VERSION" ]] || { echo "❌ 只能指定一个版本号" >&2; exit 2; }
            VERSION="$arg"
            ;;
    esac
done
source "$PROJECT_DIR/scripts/lib/command_log.sh"
COMMAND_WORKFLOW="release"
$PUBLISH && COMMAND_WORKFLOW="publish"
command_log_init "$COMMAND_WORKFLOW" "${VERSION:-auto}"
trap 'command_log_finish $?' EXIT
cd "$PROJECT_DIR"

if $AUTO_VERSION; then
	$PUBLISH && { echo "❌ 正式发布必须显式确认版本号，不能使用 --auto-version。" >&2; exit 2; }
    command_log_stage "0-计算下一版本号"
    VERSION_FILE="$(mktemp "${TMPDIR:-/tmp}/pastry-version.XXXXXX")"
    command_log_run_tail version_next 3 /bin/bash -c \
        '"$1" > "$2" || exit $?; cat "$2"' \
        _ "$PROJECT_DIR/scripts/next_version.sh" "$VERSION_FILE"
    VERSION="$(cat "$VERSION_FILE")"
    rm -f "$VERSION_FILE"
fi

if [[ -z "$VERSION" ]]; then
    echo "用法: ./release.sh <x.y.z> [--publish] [--allow-dirty] | ./release.sh --auto-version" >&2
    exit 2
fi
VERSION="${VERSION#v}"   # 统一剥掉 v 前缀，内部只用裸版本号
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || { echo "❌ 版本号必须是 x.y.z" >&2; exit 2; }
TAG="v$VERSION"
BUILD=$(git rev-list --count HEAD)
DMG_NAME="${APP_NAME}-${VERSION}.dmg"
command_log_write INFO workflow.version "version=$(command_log_value "$VERSION") auto=$AUTO_VERSION"

echo "🏭 Building $APP_NAME $VERSION (release)..."
echo ""

step() {
    echo ""
    echo "━━━ $1/8 $2 ━━━"
    command_log_stage "$1-$2"
}

# ── 检查：发布输入状态（本地验收可只放宽脏工作区）───
if $PUBLISH && $ALLOW_DIRTY; then
    echo "❌ --allow-dirty 只能用于本地制品验收，不能用于正式发布。"
    exit 1
fi
if [ -n "$(git status --porcelain)" ] && ! $ALLOW_DIRTY; then
    echo "❌ 工作区有未提交改动。请先提交。"
    exit 1
fi

EXISTING_TAG=$(git tag --points-at HEAD | head -1)
if [ -n "$EXISTING_TAG" ] && [ "$EXISTING_TAG" != "$TAG" ]; then
    echo "❌ 当前 commit 已有 tag \"$EXISTING_TAG\"，没有新代码"
    echo "ℹ️  如需强制重新发布：先 commit 改动后再运行"
    exit 1
fi

CURRENT_BRANCH=$(git branch --show-current)
if $PUBLISH && [ "$CURRENT_BRANCH" != "main" ]; then
    echo "❌ 当前分支是 \"$CURRENT_BRANCH\"，发布必须在 main 分支执行。"
    exit 1
fi

if [ "$IDENTITY" = "-" ] || ! security find-identity -v -p codesigning | grep -Fq "\"$IDENTITY\""; then
    echo "❌ 找不到稳定代码签名身份：$IDENTITY；不会回退为 ad-hoc。"
    exit 1
fi

if git rev-parse --verify --quiet "refs/tags/$TAG" >/dev/null; then
    echo "❌ 本地版本标签已存在：$TAG"
    exit 1
fi

if $PUBLISH; then
    command -v gh >/dev/null || { echo "❌ 缺少 gh CLI" >&2; exit 1; }
    git remote get-url origin >/dev/null 2>&1 || { echo "❌ 缺少 Git 远端 origin" >&2; exit 1; }
    command_log_run_tail gh_auth_status 5 gh auth status
    REPOSITORY="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"
    command_log_run_tail remote_connectivity 3 git ls-remote origin
    if git ls-remote --tags origin "refs/tags/$TAG" | grep -q .; then
        echo "❌ 远端版本标签已存在：$TAG"
        exit 1
    fi
    if gh release view "$TAG" --repo "$REPOSITORY" >/dev/null 2>&1; then
        echo "❌ GitHub Release 已存在：$TAG；拒绝覆盖正式制品。"
        exit 1
    fi
fi

cleanup() {
    local status=$?
    if [ -n "${DMG_DEVICE:-}" ]; then
        hdiutil detach "$DMG_DEVICE" -quiet 2>/dev/null || true
    elif [ -n "${DMG_VOLUME:-}" ] && [ -d "$DMG_VOLUME" ]; then
        hdiutil detach "$DMG_VOLUME" -quiet 2>/dev/null || true
    fi
    if [ -n "${SMOKE_VOLUME:-}" ] && [ -d "$SMOKE_VOLUME" ]; then
        hdiutil detach "$SMOKE_VOLUME" -quiet 2>/dev/null || true
    fi
    rm -rf "$STAGING"
    cat > "$PROJECT_DIR/Sources/Pastry/Generated/Version.generated.swift" << SWIFT
// Auto-generated by release.sh — do not edit
enum AppVersion {
    static let current = "0.0.0-dev"
    static let build = "0"
}
SWIFT
    command_log_finish "$status"
}

step 1 "统一验证"
command_log_run_tail mise_check 12 mise run check
if [ -n "$(git status --porcelain)" ] && ! $ALLOW_DIRTY; then
    echo "❌ 验证过程改变了工作区，停止发布。"
    exit 1
fi

step 2 "注入版本号"
mkdir -p "$PROJECT_DIR/Sources/Pastry/Generated"
trap cleanup EXIT

cat > "$PROJECT_DIR/Sources/Pastry/Generated/Version.generated.swift" << SWIFT
// Auto-generated by release.sh — do not edit
enum AppVersion {
    static let current = "$VERSION"
    static let build = "$BUILD"
}
SWIFT
echo "✅ 版本号已注入: $VERSION (build $BUILD)"

step 3 "Release 编译"
command_log_run_tail swift_release_build 3 swift build -c release -Xswiftc -Osize

BIN="$BUILD_DIR/$APP_NAME"
test -f "$BIN" || { echo "❌ 构建失败"; exit 1; }

step 4 "去除调试符号"
BIN_SIZE_BEFORE=$(stat -f%z "$BIN")
command_log_run_tail strip_binary 3 strip -S "$BIN"
BIN_SIZE_AFTER=$(stat -f%z "$BIN")
echo "✅ 二进制已去除调试符号: $(numfmt --to=iec $BIN_SIZE_BEFORE 2>/dev/null || echo "${BIN_SIZE_BEFORE}") → $(numfmt --to=iec $BIN_SIZE_AFTER 2>/dev/null || echo "${BIN_SIZE_AFTER}")"

step 5 "组装 .app bundle"
rm -rf "$STAGING"
mkdir -p "$STAGING/$APP_NAME.app/Contents/MacOS"
mkdir -p "$STAGING/$APP_NAME.app/Contents/Resources"

# 二进制
cp "$BIN" "$STAGING/$APP_NAME.app/Contents/MacOS/$APP_NAME"

# 资源
cp "$PROJECT_DIR/Resources/Copy.aiff"    "$STAGING/$APP_NAME.app/Contents/Resources/" 2>/dev/null || true
cp "$PROJECT_DIR/Resources/Paste.aiff"   "$STAGING/$APP_NAME.app/Contents/Resources/" 2>/dev/null || true
cp "$PROJECT_DIR/Resources/AppIcon.icns" "$STAGING/$APP_NAME.app/Contents/Resources/" 2>/dev/null || true

# SPM 资源包（Localizable.xcstrings、placeholder-icon.png 等）
cp -R "$BUILD_DIR/${APP_NAME}_${APP_NAME}.bundle" "$STAGING/$APP_NAME.app/Contents/Resources/" 2>/dev/null || true

# Info.plist
cat > "$STAGING/$APP_NAME.app/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleVersion</key>
    <string>$BUILD</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>LSMinimumSystemVersion</key>
    <string>26.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSAutoFillRequiresTextContentTypeForOneTimeCodeOnMac</key>
    <true/>
    <key>NSAppleEventsUsageDescription</key>
    <string>Pastry 需要辅助功能权限以监听全局快捷键。</string>
</dict>
</plist>
PLIST
echo "✅ .app bundle 已组装: $STAGING/$APP_NAME.app"

step 6 "代码签名"

# 固定作者级证书签名 = TCC/Keychain 授权持久保留
# 默认使用 Nekutai；通过 CODESIGN_IDENTITY 环境变量指定其他自签名或开发者账号证书。
if [ "$IDENTITY" = "-" ]; then
    echo "❌ Pastry 需要稳定代码签名以保留辅助功能授权，不能使用 ad-hoc 签名。"
    echo "   请创建自签名代码签名证书，或设置 CODESIGN_IDENTITY 为开发者账号证书。"
    exit 1
fi
echo "🔐 签名身份: $IDENTITY"

# 公证提醒（需要付费开发者账号）
# 有账号后加一行：
#   xcrun notarytool submit "$DMG_PATH" --keychain-profile "AC_PASSWORD" --wait

if ! command_log_run codesign_app codesign --force --deep --sign "$IDENTITY" "$STAGING/$APP_NAME.app"; then
    echo "❌ \"$IDENTITY\" 签名失败。Pastry 不会改用 ad-hoc，因为这会破坏辅助功能授权体验。"
    echo "   请检查钥匙串中是否存在该代码签名证书，或通过 CODESIGN_IDENTITY 指定稳定证书。"
    exit 1
fi
command_log_run verify_release "$PROJECT_DIR/scripts/verify_release.sh" "$STAGING/$APP_NAME.app" "$VERSION"

step 7 "DMG 打包和烟测"
mkdir -p "$DIST_DIR"
DMG_PATH="$DIST_DIR/$DMG_NAME"
rm -f "$DMG_PATH"

# 创建临时 DMG 目录
DMG_SRC="$STAGING/dmg_root"
mkdir -p "$DMG_SRC"
cp -R "$STAGING/$APP_NAME.app" "$DMG_SRC/"
ln -s /Applications "$DMG_SRC/Applications" 2>/dev/null || true
mkdir -p "$DMG_SRC/.background"
cp "$PROJECT_DIR/Resources/dmg-background.png" "$DMG_SRC/.background/background.png"
cp "$PROJECT_DIR/Resources/dmg-background@2x.png" "$DMG_SRC/.background/background@2x.png"
if command -v SetFile >/dev/null 2>&1; then
    SetFile -a V "$DMG_SRC/.background"
fi

# 计算 DMG 大小
DMG_SIZE_KB=$(du -sk "$DMG_SRC" | cut -f1)
DMG_SIZE_MB=$(( (DMG_SIZE_KB + 1023) / 1024 + 8 ))

command_log_run_tail hdiutil_create 1 hdiutil create -volname "$APP_NAME" \
    -srcfolder "$DMG_SRC" \
    -ov -format UDRW \
    -size ${DMG_SIZE_MB}m \
    "$STAGING/tmp.dmg"

# DMG 美化（挂载最终可写镜像，由 Finder 现场生成与当前卷匹配的布局）
echo "🎨 美化 DMG..."

DMG_VOLUME="$STAGING/dmg-mount"
mkdir -p "$DMG_VOLUME"
command_log_run_tail hdiutil_attach_writable 3 hdiutil attach "$STAGING/tmp.dmg" \
    -readwrite -noverify -noautoopen -mountpoint "$DMG_VOLUME"
command_log_run layout_dmg osascript "$PROJECT_DIR/scripts/layout_dmg.applescript" \
    "$DMG_VOLUME" "$APP_NAME"
[ -f "$DMG_VOLUME/.DS_Store" ] || { echo "❌ Finder 未生成 DMG 布局记录"; exit 1; }
[ -f "$DMG_VOLUME/.background/background.png" ] || { echo "❌ DMG 背景文件缺失"; exit 1; }
sync

# 卸载
if ! command_log_run_tail hdiutil_detach_writable 3 hdiutil detach "$DMG_VOLUME" -quiet; then
    echo "❌ DMG 美化后卸载失败: $DMG_VOLUME"
    exit 1
fi
DMG_VOLUME=""
echo "✅ DMG 背景和窗口布局已写入"

# 转换为只读压缩 DMG
CONVERT_LOG="$STAGING/dmg-convert.log"
if ! command_log_run_tail hdiutil_convert 3 /bin/bash -c \
    'hdiutil convert "$1" -format UDZO -o "$2" > "$3" 2>&1' \
    _ "$STAGING/tmp.dmg" "$DMG_PATH" "$CONVERT_LOG"; then
    echo "❌ DMG 压缩转换失败"
    cat "$CONVERT_LOG"
    exit 1
fi
tail -1 "$CONVERT_LOG"
rm -f "$STAGING/tmp.dmg"
echo "✅ DMG 已生成: $DMG_PATH"
command_log_artifact dmg "$DMG_PATH"
command_log_run_tail hdiutil_verify 3 hdiutil verify "$DMG_PATH"
CHECKSUM_PATH="$DMG_PATH.sha256"
shasum -a 256 "$DMG_PATH" > "$CHECKSUM_PATH"
command_log_artifact checksum "$CHECKSUM_PATH"
command_log_run release_smoke "$PROJECT_DIR/scripts/release_smoke.sh" "$DMG_PATH" "$VERSION"

if $PUBLISH; then
    step 8 "发布到 GitHub Releases"
    
    git tag -a "$TAG" -m "$APP_NAME $VERSION"
    if ! command_log_run_tail git_push_atomic 5 git push --atomic origin "HEAD:refs/heads/main" "refs/tags/$TAG"; then
        git tag -d "$TAG" >/dev/null
        echo "❌ 分支与标签推送失败，本地标签已回滚。"
        exit 1
    fi
    if ! command_log_run gh_release_create gh release create "$TAG" \
        --repo "$REPOSITORY" --title "$APP_NAME $VERSION" --generate-notes \
        "$DMG_PATH" "$CHECKSUM_PATH"; then
        git push origin ":refs/tags/$TAG" >/dev/null 2>&1 || true
        git tag -d "$TAG" >/dev/null
        echo "❌ GitHub Release 创建失败，本轮标签已回滚；已推送的 main 保留。"
        exit 1
    fi
    
    echo "✅ 发布完成"
    RELEASE_URL_FILE="$STAGING/release-url.txt"
    command_log_run_tail gh_release_url 3 /bin/bash -c \
        'gh release view "$1" --json url -q '\''.url'\'' > "$2"' \
        _ "$TAG" "$RELEASE_URL_FILE"
    echo "🔗 $(cat "$RELEASE_URL_FILE")"
else
    step 8 "跳过 GitHub Releases 发布"
    echo "ℹ️  未传入 --publish，仅生成本地 DMG。"
fi

echo ""
echo "╔══════════════════════════════════════╗"
echo "║  ✅ Release $VERSION 完成              ║"
echo "╠══════════════════════════════════════╣"
printf "║  📦 %-32s ║\n" "$DMG_NAME"
DMG_SIZE=$(stat -f%z "$DMG_PATH" 2>/dev/null || echo 0)
DMG_MB=$((DMG_SIZE / 1048576))
printf "║  📏 DMG: %d MB                        ║\n" $DMG_MB
DMG_SHA=$(shasum -a 256 "$DMG_PATH" | awk '{print $1}')
printf "║  🔐 SHA256: %.23s…        ║\n" "$DMG_SHA"
echo "╚══════════════════════════════════════╝"
echo "SHA256 ($DMG_NAME): $DMG_SHA"
