#!/bin/bash
# Pastry Release — 生产发布
# 流程：release 编译 → 去除符号 → DMG 打包 → 签名
# 用法: ./release.sh [version] [--publish]
#   ./release.sh 1.0.1              # 仅构建 DMG
#   ./release.sh 1.0.1 --publish    # 构建 + 推 tag + 创建 GitHub Release
#   ./release.sh                    # 自动取 git tag，没有则用 1.0
set -e

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_NAME="Pastry"
BUILD_DIR="$PROJECT_DIR/.build/release"
STAGING="$PROJECT_DIR/.release_staging"
BUNDLE_ID="com.nekutai.pastry"
VERSION="${1:-$(git describe --tags --abbrev=0 2>/dev/null || echo '1.0')}"
VERSION="${VERSION#v}"   # 统一剥掉 v 前缀，内部只用裸版本号
BUILD=$(git rev-list --count HEAD)
DMG_NAME="${APP_NAME}-${VERSION}.dmg"
IDENTITY="${CODESIGN_IDENTITY:-Pastry Release}"  # 默认固定证书（TCC 持久），用 CODESIGN_IDENTITY 环境变量覆盖

# 解析 --publish 标志
PUBLISH=false
for arg in "$@"; do
    [[ "$arg" == "--publish" ]] && PUBLISH=true
done

echo "🏭 Building $APP_NAME $VERSION (release)..."
echo ""

# ── 检查：是否有新代码（--force 跳过）───
FORCE=false
for arg in "$@"; do
    [[ "$arg" == "--force" ]] && FORCE=true
done
EXISTING_TAG=$(git tag --points-at HEAD | head -1)
if [ -n "$EXISTING_TAG" ] && [ "$EXISTING_TAG" != "v$VERSION" ] && ! $FORCE; then
    echo "❌ 当前 commit 已有 tag \"$EXISTING_TAG\"，没有新代码"
    echo "   如需强制重新发布：先 commit 改动后再运行"
    exit 1
fi

cd "$PROJECT_DIR"

# ── 0. 注入版本号到编译时代码（构建后恢复 dev 版本） ──
mkdir -p "$PROJECT_DIR/Sources/Pastry/Generated"
DEV_VERSION="${VERSION}-dev"
trap 'cat > "$PROJECT_DIR/Sources/Pastry/Generated/Version.generated.swift" << SWIFT
// Auto-generated by release.sh — do not edit
enum AppVersion {
    static let current = "'"$DEV_VERSION"'"
    static let build = "0"
}
SWIFT' EXIT

cat > "$PROJECT_DIR/Sources/Pastry/Generated/Version.generated.swift" << SWIFT
// Auto-generated by release.sh — do not edit
enum AppVersion {
    static let current = "$VERSION"
    static let build = "$BUILD"
}
SWIFT

# ── 1. Release 编译（启用优化，去除 assert） ──
echo "━━━ 1/5 Release 编译 ━━━"
swift build -c release -Xswiftc -Osize 2>&1 | tail -3

BIN="$BUILD_DIR/$APP_NAME"
test -f "$BIN" || { echo "❌ 构建失败"; exit 1; }

# ── 2. 去除符号 ──
echo ""
echo "━━━ 2/5 去除调试符号 ━━━"
BIN_SIZE_BEFORE=$(stat -f%z "$BIN")
strip -S "$BIN" 2>/dev/null || true
BIN_SIZE_AFTER=$(stat -f%z "$BIN")
echo "   二进制: $(numfmt --to=iec $BIN_SIZE_BEFORE 2>/dev/null || echo "${BIN_SIZE_BEFORE}") → $(numfmt --to=iec $BIN_SIZE_AFTER 2>/dev/null || echo "${BIN_SIZE_AFTER}")"

# ── 3. 组装 .app ──
echo ""
echo "━━━ 3/5 组装 .app bundle ━━━"
rm -rf "$STAGING"
mkdir -p "$STAGING/$APP_NAME.app/Contents/MacOS"
mkdir -p "$STAGING/$APP_NAME.app/Contents/Resources"

# 二进制
cp "$BIN" "$STAGING/$APP_NAME.app/Contents/MacOS/$APP_NAME"
# 同时复制裸二进制到项目根（用于上传到 GitHub Release）
cp "$BIN" "$PROJECT_DIR/$APP_NAME"

# 资源
cp "$PROJECT_DIR/Resources/Copy.aiff"    "$STAGING/$APP_NAME.app/Contents/Resources/" 2>/dev/null || true
cp "$PROJECT_DIR/Resources/Paste.aiff"   "$STAGING/$APP_NAME.app/Contents/Resources/" 2>/dev/null || true
cp "$PROJECT_DIR/Resources/AppIcon.icns" "$STAGING/$APP_NAME.app/Contents/Resources/" 2>/dev/null || true

# Info.plist
cat > "$STAGING/$APP_NAME.app/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundleExecutable</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleVersion</key>
    <string>$BUILD</string>
    <key>CFBundleShortVersionString</key>
    <string>$VERSION</string>
    <key>LSMinimumSystemVersion</key>
    <string>26.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSAppleEventsUsageDescription</key>
    <string>Pastry 需要辅助功能权限以监听全局快捷键。</string>
</dict>
</plist>
PLIST

# ── 4. 代码签名 ──
echo ""
echo "━━━ 4/5 代码签名 ━━━"

# 固定证书签名 = TCC 权限持久保留（更新不需要重新授权）
# 首次运行需手动创建一次（30 秒）：
#   Keychain Access → 证书助理 → 创建证书
#   名称: Pastry Release（或自定义），身份类型: 自签名根，证书类型: 代码签名
#   分发正式签名：CODESIGN_IDENTITY='Developer ID Application: ...' ./release.sh
CERT_OK=true
if security find-identity -p codesigning 2>/dev/null | grep -qF "$IDENTITY"; then
    echo "   签名身份: $IDENTITY"
else
    echo "⚠️  未找到 \"$IDENTITY\" 代码签名证书"
    if [ "$IDENTITY" = "Pastry Release" ]; then
        echo "   首次运行需创建一次（后续永久有效）："
        echo "   Keychain Access → 菜单「证书助理」→「创建证书」"
        echo "   名称: Pastry Release  |  类型: 代码签名"
    fi
    echo "   本次回退到 ad-hoc 签名（TCC 不持久）"
    CERT_OK=false
fi

# 公证提醒（需要付费开发者账号）
# 有账号后加一行：
#   xcrun notarytool submit "$DMG_PATH" --keychain-profile "AC_PASSWORD" --wait

if $CERT_OK; then
    codesign --force --deep --sign "$IDENTITY" "$STAGING/$APP_NAME.app" 2>&1
else
    codesign --force --deep --sign - "$STAGING/$APP_NAME.app" 2>&1
fi

# ── 5. DMG 打包（含自定义背景 + 图标布局）───
echo ""
echo "━━━ 5/6 DMG 打包 ━━━"
DMG_PATH="$PROJECT_DIR/$DMG_NAME"
rm -f "$DMG_PATH"

# 创建临时 DMG 目录
DMG_SRC="$STAGING/dmg_root"
mkdir -p "$DMG_SRC"
cp -R "$STAGING/$APP_NAME.app" "$DMG_SRC/"
ln -s /Applications "$DMG_SRC/Applications" 2>/dev/null || true

# 计算 DMG 大小（.app 大小 + 背景图 + 余量）
APP_SIZE_KB=$(du -sk "$DMG_SRC/$APP_NAME.app" | cut -f1)
DMG_SIZE_MB=$(( (APP_SIZE_KB / 1024) + 20 ))  # +20MB 留给背景和余量

hdiutil create -volname "$APP_NAME" \
    -srcfolder "$DMG_SRC" \
    -ov -format UDRW \
    -size ${DMG_SIZE_MB}m \
    "$STAGING/tmp.dmg" 2>&1 | grep -E "created|failed" || true

# ── 6. DMG 美化（背景图 + 图标位置）───
echo ""
echo "━━━ 6/6 DMG 美化 ━━━"

# 挂载
hdiutil attach -readwrite -noverify -noautoopen "$STAGING/tmp.dmg" > /dev/null 2>&1
VOLUME="/Volumes/$APP_NAME"
if [ ! -d "$VOLUME" ]; then
    echo "❌ 挂载失败"
    exit 1
fi

# 复制背景图（含 Retina @2x）
mkdir -p "$VOLUME/.background"
cp "$PROJECT_DIR/Resources/dmg-background.png" "$VOLUME/.background/background.png"
cp "$PROJECT_DIR/Resources/dmg-background@2x.png" "$VOLUME/.background/background@2x.png"

# 用 AppleScript 设置窗口属性（不打开窗口，避免闪现）
osascript << 'APPLESCRIPT'
tell application "Finder"
    tell disk "Pastry"
        set current view of container window to icon view
        set toolbar visible of container window to false
        set statusbar visible of container window to false
        set the bounds of container window to {400, 200, 940, 578}
        set viewOptions to the icon view options of container window
        set arrangement of viewOptions to not arranged
        set icon size of viewOptions to 96
        set background picture of viewOptions to file ".background:background.png"
        set position of item "Pastry.app" of container window to {48, 124}
        set position of item "Applications" of container window to {394, 124}
        update without registering applications
    end tell
end tell
APPLESCRIPT

# 等待 Finder 写入 .DS_Store
sleep 0.5

# 卸载
hdiutil detach "$VOLUME" -quiet

# 转换为只读压缩 DMG
hdiutil convert "$STAGING/tmp.dmg" -format UDZO -o "$DMG_PATH" 2>&1 | tail -1
rm -f "$STAGING/tmp.dmg"

# 清理
rm -rf "$STAGING"

# ── 6. 发布到 GitHub Releases（可选） ──
if $PUBLISH; then
    echo ""
    echo "━━━ 6/6 发布到 GitHub Releases ━━━"
    
    if ! command -v gh &>/dev/null; then
        echo "❌ 未安装 gh CLI，请先运行: brew install gh && gh auth login"
        exit 1
    fi
    
    if ! gh auth status &>/dev/null; then
        echo "❌ gh 未登录，请先运行: gh auth login"
        exit 1
    fi
    
    TAG="$VERSION"
    
    # 创建 tag 并推送
    if git rev-parse "$TAG" &>/dev/null; then
        echo "   ⚠️  tag $TAG 已存在，跳过创建"
    else
        echo "   🏷  创建 tag $TAG..."
        git tag "$TAG"
    fi
    
    git push origin main "$TAG" 2>&1 | tail -2
    
    # 检查是否已有同名 Release
    if gh release view "$TAG" &>/dev/null 2>&1; then
        echo "   ⚠️  Release $TAG 已存在，仅上传资产..."
        gh release upload "$TAG" "$DMG_PATH" "$PROJECT_DIR/$APP_NAME" --clobber
    else
        echo "   📦 创建 Release $TAG..."

        # 生成更新日志：从上一个 tag 到 HEAD 的 Conventional Commits
        last_tag=$(git describe --tags --abbrev=0 HEAD~ 2>/dev/null || echo "")
        if [[ -n "$last_tag" ]]; then
            changelog=$(git log "${last_tag}..HEAD" --pretty=format:"- %s" --no-merges 2>/dev/null)
            if [[ -z "$changelog" ]]; then
                changelog="- $APP_NAME $VERSION 发布"
            fi
        else
            changelog="- $APP_NAME $VERSION 发布"
        fi

        gh release create "$TAG" \
            --title "$APP_NAME $VERSION" \
            --notes "$changelog" \
            "$DMG_PATH" \
            "$PROJECT_DIR/$APP_NAME"
    fi
    
    echo "   ✅ 发布完成"
    echo "   🔗 $(gh release view "$TAG" --json url -q '.url')"
fi

echo ""
echo "╔══════════════════════════════════════╗"
echo "║  ✅ Release $VERSION 完成              ║"
echo "╠══════════════════════════════════════╣"
printf "║  📦 %-32s ║\n" "$DMG_NAME"
BIN_KB=$((BIN_SIZE_AFTER / 1024))
DMG_SIZE=$(stat -f%z "$DMG_PATH" 2>/dev/null || echo 0)
DMG_MB=$((DMG_SIZE / 1048576))
printf "║  📏 二进制: %d KB  DMG: %d MB      ║\n" $BIN_KB $DMG_MB
echo "╚══════════════════════════════════════╝"
